[package]
name = "rcocktail"
version = "0.1.0"
authors = ["Ruben Robles <d8vjork@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
